// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJ7hqEky3X41HRUiWDedrAyri6yNoKiY',
    appId: '1:1047926014999:web:412ae888106597e788c852',
    messagingSenderId: '1047926014999',
    projectId: 'note-project-f2870',
    authDomain: 'note-project-f2870.firebaseapp.com',
    storageBucket: 'note-project-f2870.appspot.com',
    measurementId: 'G-DD4V66D95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrynjgDlVjVhJfxvnJHSNQO8URs12toFc',
    appId: '1:1047926014999:android:294877baac759a2488c852',
    messagingSenderId: '1047926014999',
    projectId: 'note-project-f2870',
    storageBucket: 'note-project-f2870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfk7kAW2Ud9jUTsoAqjMzt-qgxYM-ZpOo',
    appId: '1:1047926014999:ios:76ef5393cb92b94388c852',
    messagingSenderId: '1047926014999',
    projectId: 'note-project-f2870',
    storageBucket: 'note-project-f2870.appspot.com',
    iosClientId: '1047926014999-84a12o0d5p71ot35e9ebrj9o0fcig2h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfk7kAW2Ud9jUTsoAqjMzt-qgxYM-ZpOo',
    appId: '1:1047926014999:ios:28cf9725bae05ef988c852',
    messagingSenderId: '1047926014999',
    projectId: 'note-project-f2870',
    storageBucket: 'note-project-f2870.appspot.com',
    iosClientId: '1047926014999-34uo9im8d1hjrmslah54c9f536nop449.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteAppFlutter.RunnerTests',
  );
}
